version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
    networks:
      - mynetwork
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: mydatabase
    ports:
      - "27018:27018"
    networks:
      - mynetwork
    command: mongod --port 27018
networks:
  mynetwork:
    driver: bridge
