# version: '3'
# services:
#   backend:
#     build:
#       context: ./backend
#     ports:
#       - "5001:5001"
#     depends_on:
#       - mongodb
#     networks:
#       - mynetwork
#   mongodb:
#     image: mongo
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: root
#       MONGO_INITDB_ROOT_PASSWORD: example
#       MONGO_INITDB_DATABASE: mydatabase
#     ports:
#       - "27018:27018"
#     networks:
#       - mynetwork
#     command: mongod --port 27018
#   mongo-seed:
#     build:
#       context: .
#       dockerfile: ./Dockerfile-mongo-seed
#     depends_on:
#       - mongodb
#     networks:
#       - mynetwork
# networks:
#   mynetwork:
#     driver: bridge

version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
    networks:
      - mynetwork
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: mydatabase
    ports:
      - "27018:27018"
    networks:
      - mynetwork
    command: mongod --port 27018
  mongo-seed:
    build:
      context: .
      dockerfile: ./Dockerfile-mongo-seed
    depends_on:
      - mongodb
    networks:
      - mynetwork
  client:
    build:
      context: ./client
    ports:
      - "8080:8080"
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge
