FROM python:3.10.9-slim-buster
RUN apt-get update && apt-get install -y build-essential
WORKDIR /app

RUN pip install --upgrade pip

COPY ./requirements.txt /app/requirements.txt

RUN pip install -r requirements.txt

COPY . /app
ENTRYPOINT [ "python" ]
CMD [ "main.py"]
